- name: Setup Hostname
  shell: set-hostname {{COMPONENT}}

- name: Disable Auto Shutdown
  shell: disable-auto-shutdown

 - name: Install Prometheus Node Exporter
   shell: curl -s https://github.com/linuxautomations/labautomation/blob/master/tools/prometheus-node-exporter/install.sh | bash